In [1]:
import numpy as np
from sklearn.datasets import load_iris


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [2]:
from sklearn.model_selection import train_test_split
 
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], test_size = 0.2)
# 데이터셋을 랜덤하게 80%의 훈련셋과 20%의 테스트셋으로 분리합니다.
 
print(X_train)
 
print(y_train)


[[4.9 3.1 1.5 0.2]
 [6.3 2.5 5.  1.9]
 [7.7 3.  6.1 2.3]
 [7.  3.2 4.7 1.4]
 [5.7 2.8 4.5 1.3]
 [5.5 3.5 1.3 0.2]
 [5.8 2.6 4.  1.2]
 [5.2 2.7 3.9 1.4]
 [6.7 3.  5.2 2.3]
 [4.7 3.2 1.3 0.2]
 [5.  2.3 3.3 1. ]
 [7.4 2.8 6.1 1.9]
 [7.3 2.9 6.3 1.8]
 [7.7 3.8 6.7 2.2]
 [6.  2.9 4.5 1.5]
 [5.4 3.  4.5 1.5]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 4.4 1.4]
 [6.  3.  4.8 1.8]
 [5.5 2.6 4.4 1.2]
 [7.2 3.6 6.1 2.5]
 [6.2 2.2 4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [5.1 3.5 1.4 0.2]
 [6.5 3.  5.5 1.8]
 [6.1 2.6 5.6 1.4]
 [6.5 3.2 5.1 2. ]
 [5.8 2.8 5.1 2.4]
 [4.4 3.  1.3 0.2]
 [6.  2.2 4.  1. ]
 [5.2 3.5 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [6.4 2.8 5.6 2.1]
 [6.5 3.  5.8 2.2]
 [4.9 3.6 1.4 0.1]
 [5.  3.4 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [6.3 3.3 6.  2.5]
 [6.9 3.2 5.7 2.3]
 [4.8 3.4 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [4.4 3.2 1.3 0.2]
 [6.4 3.2 5.3 2.3]
 [6.9 3.1 5.1 2.3]
 [6.1 2.8 4.7 1.2]
 [5.7 4.4 1.5 0.4]
 [6.4 2.9 4.3 1.3]
 [4.7 3.2 1.6 0.2]
 [6.2 2.8 4.8 1.8]
 [6.4 3.1 5.5 1.8]
 [6.  2.2 5.  1.5]
 [5.7 2.5 5.

In [9]:
import pandas as pd

df = pd.read_table('C:/BCI Data/ratio file/hyejin_all_ratio.xlsx',sep='\t',encoding = 'euc-kr')

UnicodeDecodeError: 'euc_kr' codec can't decode byte 0x82 in position 16: illegal multibyte sequence

In [ ]:
 
print("특성1 범위: ", "[", min(X_train[:, 0]), ",", max(X_train[:, 0]), "]")
print("특성2 범위: ", "[", min(X_train[:, 1]), ",", max(X_train[:, 1]), "]")
print("특성3 범위: ", "[", min(X_train[:, 2]), ",", max(X_train[:, 2]), "]")
print("특성4 범위: ", "[", min(X_train[:, 3]), ",", max(X_train[:, 3]), "]")
 
from sklearn.preprocessing import StandardScaler
 
sc = StandardScaler()
sc.fit(X_train)
 
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
print("표준화된 특성1 범위: ", "[", min(X_train_std[:, 0]), ",", max(X_train_std[:, 0]), "]")
print("표준화된 특성2 범위: ", "[", min(X_train_std[:, 1]), ",", max(X_train_std[:, 1]), "]")
print("표준화된 특성3 범위: ", "[", min(X_train_std[:, 2]), ",", max(X_train_std[:, 2]), "]")
print("표준화된 특성4 범위: ", "[", min(X_train_std[:, 3]), ",", max(X_train_std[:, 3]), "]")
 
from sklearn.svm import SVC
 
svm_model = SVC(kernel='rbf', C=8, gamma=0.1)
 
svm_model.fit(X_train_std, y_train) # SVM 분류 모델 훈련
 
y_pred = svm_model.predict(X_test_std) # 테스트
 
print("예측된 라벨:", y_pred)
print("ground-truth 라벨:", y_test)
 
print("prediction accuracy: {:.2f}".format(np.mean(y_pred == y_test))) # 예측 정확도